version: "3.7"
services:
  notebook:
    container_name: archimedic_notebook
    image: chrisdare/archimedic:latest
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=${JUPYTER_TOKEN?Variable not set}"]
    ports:
      - 8888:8888
    env_file:
      - .env
    volumes:
      - .:/app

  api:
    container_name: archimedic_api
    image: chrisdare/archimedic:latest
    command: ["sh", "/start-reload.sh"]
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - .:/app

  demo:
    container_name: archimedic_demo
    image: chrisdare/archimedic:latest
    command: ["streamlit", "run", "demo.py", "--server.port", "8501"]
    ports:
      - 8501:8501
    env_file:
      - .env
    volumes:
      - .:/app
